repo_username: <edb-yum-repo-username>
repo_password: <edb-yum-repo-password>
tpa_subscription_token: <tpa-subscription-token>
tpa_bin_path: /opt/EDB/TPA/bin
pg_version: 14
pg_type: PostgreSQL
postgres_user: postgres
postgres_group: postgres
pg_bin_path: /usr/pgsql/14/bin
bdr_writers: 16
bdr_wal_decoder: false
# /!\ DO NOT CHANGE bdr_dbname VALUE /!\
bdr_dbname: bdrdb
